services:
  web-asset-build:
    build:
      context: .
      target: build-assets
    volumes:
      - './root/static/:/build/root/static/'
      - 'web-assets:/build/root/assets/'
    command: ['./build-assets.mjs', '--watch']
  web-server:
    build:
      context: .
      target: develop
    volumes:
      - './:/app/'
      - 'web-assets:/app/root/assets/'
      - '/app/local'
    ports:
      - '5001:80'
    environment:
      # default is 120, shorten to work with compose label
      COLUMNS: 96
    depends_on:
      - web-asset-build
    develop:
      watch:
        - path: ./cpanfile
          action: rebuild
volumes:
  web-assets:
