exclude = [
    "/.build/**",
    "/blib/**",
    "/root/assets/**",
    "/local/**",
]

[commands.perlimports]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perlimports" ]
lint-flags = ["--lint" ]
tidy-flags = ["-i" ]
ok-exit-codes = 0
expect-stderr = true

[commands.perlcritic]
type = "lint"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perlcritic", "--profile=$PRECIOUS_ROOT/.perlcriticrc" ]
ok-exit-codes = 0
lint-failure-exit-codes = 2

[commands.perltidy]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perltidy", "--profile=$PRECIOUS_ROOT/.perltidyrc" ]
lint-flags = [ "--assert-tidy", "--no-standard-output", "--outfile=/dev/null" ]
tidy-flags = [ "--backup-and-modify-in-place", "--backup-file-extension=/" ]
ok-exit-codes = 0
lint-failure-exit-codes = 2
ignore-stderr = "Begin Error Output Stream"

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort", "path", "--unique" ]
lint-flags = "--check"
tidy-flags = "--in-place"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = [
    "The .+ file is not sorted",
    "The .+ file is not unique",
]

[commands.prettier]
type    = "both"
include = [ "**/*.md", "**/*.yml", "**/*.yaml", "**/*.css", "**/*.less", "**/*.scss" ]
cmd     = [
    "npx", "-s", "prettier"
]
lint-flags = "--check"
tidy-flags = "--write"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = [ "Code style issues" ]

[commands.js-beautify-tidy]
type    = "tidy"
include = [ "**/*.js", "**/*.mjs" ]
cmd     = [
    "npx", "-s", "js-beautify",
    "--editorconfig",
    "--brace-style", "end-expand",
    "--replace"
]
ok-exit-codes = 0
lint-failure-exit-codes = 1

[commands.js-beautify-lint]
type    = "lint"
include = [ "**/*.js", "**/*.mjs" ]
cmd     = [
    "bash", "-c", """
    diff -u "$0" <( \
        npx -s js-beautify \
        --editorconfig \
        --brace-style end-expand \
        "$0" \
    ) >&2
    """
]
ok-exit-codes = 0
lint-failure-exit-codes = 1

[commands.eslint]
type    = "lint"
include = [ "**/*.js", "**/*.mjs" ]
cmd     = [
    "npx", "-s", "eslint"
]
ok-exit-codes = 0
lint-failure-exit-codes = 1
